In [2]:
import pytrade

In [6]:
df = pytrade.get_data(reload = False)

In [ ]:
stonks = pytrade.Portfolio("stonks", df)
stonks.autosave = True
stonks.deposit(100000)
stonks.buy("XOM", 1000, 90)
stonks.sell("XOM", 5, 45)
print(stonks.buy_power)
stonks.report()

In [ ]:
stonks.current_value()

In [ ]:
stonks.buy("XOM", 3, 12)

In [ ]:
print(stonks.buy_power)
for stock in stonks.stocks:
    print(stock)

In [ ]:

stonks.save()

In [ ]:
stonks.buy("AAPL", 1, 90)

In [ ]:
for stock in stonks.stocks:
    print(stock)

In [11]:
load_stonks = pytrade.Portfolio.load("stonks", df)

In [12]:
load_stonks.context

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XRX,XYL,YUM,ZBH,ZBRA,ZION,ZTS,^DJI,^GSPC,^IXIC
Date,,,,,,,,,,,,,,,,,,,,,
2018-07-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-07-16,61.618176,36.490562,138.480774,185.829773,86.355568,83.708817,419.380005,60.014519,162.686340,254.679993,...,23.013897,65.691948,75.978409,110.830544,146.800003,49.435993,83.550438,25064.359375,2798.429932,7805.720215
2018-07-17,61.932545,36.588451,139.085556,186.355377,85.601929,83.631744,427.369995,61.005379,163.103638,258.309998,...,23.041546,66.081810,76.036346,111.942490,148.220001,50.068214,84.725945,25119.890625,2809.550049,7855.120117
2018-07-18,61.883430,37.557487,138.778229,185.333313,84.695755,83.159752,431.549988,62.899654,161.463577,259.779999,...,23.345695,66.461922,76.780098,110.584557,149.089996,51.087311,84.903755,25199.289062,2815.620117,7854.439941
2018-07-19,63.023041,37.322571,142.149261,186.773956,80.703201,82.418030,425.989990,61.957371,161.958496,257.679993,...,23.207443,66.842049,76.625549,110.446785,148.949997,50.200317,84.504089,25064.500000,2804.489990,7825.299805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-07-07,89.209999,11.910000,136.679993,372.690002,99.349998,98.300003,264.589996,92.459999,216.330002,449.359985,...,15.130000,66.089996,86.860001,117.000000,254.259995,31.540001,138.440002,25890.179688,3145.320068,10343.889648
2020-07-08,89.540001,11.990000,136.449997,381.369995,99.279999,97.209999,265.640015,92.580002,218.889999,457.679993,...,15.420000,65.739998,86.550003,118.919998,257.209991,31.680000,138.809998,26067.279297,3169.939941,10492.500000
2020-07-09,89.919998,11.180000,133.750000,383.010010,97.940002,96.389999,265.679993,93.669998,219.309998,460.839996,...,14.630000,66.519997,86.379997,117.639999,262.010010,30.440001,137.679993,25706.089844,3152.050049,10547.750000
2020-07-10,89.419998,11.940000,134.449997,383.679993,96.830002,97.050003,264.510010,93.040001,220.259995,466.200012,...,15.490000,66.510002,87.239998,119.430000,260.670013,32.209999,137.100006,26075.300781,3185.040039,10617.440430
2020-07-13,89.260002,11.630000,135.130005,381.910004,97.860001,97.269997,264.549988,93.089996,215.740005,442.470001,...,15.840000,67.339996,87.430000,120.870003,255.500000,32.880001,138.309998,26085.800781,3155.219971,10390.843750

In [ ]:

function(1, 2, animal="cat")